name: advance_text_controller
description: A Flutter package that provides advanced text editing controllers for managing and formatting various types of inputs, including dates, times, models, and numerical values.
repository: https://github.com/Prashant4900/advance_text_controller
issue_tracker: https://github.com/Prashant4900/advance_text_controller/issues?q=is%3Aissue+is%3Aopen
version: 0.0.1

environment:
  sdk: ^3.4.0
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
